### PR TITLE
gormschema: support customize JoinTable

### LINKED ISSUE #39: [Defect] Handle Customize JoinTable
I believe it is not the right way to handle a Customized JoinTable when you run migration. 
https://github.com/ariga/atlas-provider-gorm/blob/e5d6dbfb61aaf99a784b5f8641a8bcace527f1e7/gormschema/gorm.go#L143-L144

The document [mentions](https://gorm.io/docs/many_to_many.html#Customize-JoinTable) that you need to run `db.SetupJoinTable()` in order to create a relationship for Customized JoinTable, and then exclude that from the AutoMigrate method.

I have checked out [this unit test](https://github.com/go-gorm/gorm/blob/d0b4ceb726f254599c250df2eb7ee9bb86d8a68a/tests/associations_test.go#L334-L340) as a reference.

image

Therefore, there is no problem with #34, we just need to define `db.SetupJoinTable()`, and then `Load(User, Role)` only.

Adding new logic may introduce unintended and unexpected bugs in the feature.

### PR DESCRIPTION
**Pull request by luantranminh**
Fix #39

### CODE REVIEW

**Comment by luantranminh** [comment]
@ronenlu 👀  Could you have a look? Happy to discuss more

**Comment by ronenlu** [comment]
> @ronenlu 👀 Could you have a look? Happy to discuss more

@luantranminh  Thank you for your contribution! I will review the PR sonn

File: gormschema/gorm.go [hunk 1]
```diff
@@ -28,8 +27,9 @@ func New(dialect string, opts ...Option) *Loader {
 type (
 	// Loader is a Loader for gorm schema.
 	Loader struct {
-		dialect string
-		config  *gorm.Config
+		dialect            string
+		config             *gorm.Config
+		joinTableCallbacks []func(*gorm.DB)
```
Comment (giautm) [inline gormschema/gorm.go:32]:
```suggestion
	modify func(*gorm.DB)
```

File: gormschema/gorm.go [hunk 2]
```diff
@@ -85,6 +85,11 @@ func (l *Loader) Load(models ...any) (string, error) {
 	if l.dialect != "sqlite" {
 		db.Config.DisableForeignKeyConstraintWhenMigrating = true
 	}
+
+	for _, setupJoinTable := range l.joinTableCallbacks {
+		setupJoinTable(db)
+	}
```
Comment (giautm) [inline gormschema/gorm.go:91]:
```suggestion
if l.modifier != nil {
  // Allow the user to modify the database schema with SetupJoinTable()
  // or adding view via Migrator().CreateView()
  l.modifier(db)
}
```

File: gormschema/gorm.go [hunk 3]
```diff
@@ -163,3 +166,19 @@ func (m *migrator) CreateConstraints(models []any) error {
...
+
+func (l *Loader) WithJoinTables(params ...SetupJoinTableParams) *Loader {
+	for _, p := range params {
+		l.joinTableCallbacks = append(l.joinTableCallbacks, func(db *gorm.DB) {
+			db.SetupJoinTable(p.Model, p.Field, p.JoinTable)
+		})
+	}
+
+	return l
+}
```
Comment (giautm) [inline gormschema/gorm.go:184]: No need
```suggestion
```

File: gormschema/gorm.go (hunk 1 above)
Comment (luantranminh) [reply gormschema/gorm.go:32]: I chose a specific name for this modifier because I'm not sure if in the future we will have another modifier that runs after db.AutoMigrate

Comment (giautm) [reply gormschema/gorm.go:32]: Let call it BeforeMigrate/AfterMigrate

File: gormschema/gorm.go [hunk 4]
```diff
@@ -163,3 +166,8 @@ func (m *migrator) CreateConstraints(models []any) error {
 	}
 	return nil
 }
+
+func (l *Loader) BeforeAutoMigrate(cb func(*gorm.DB)) *Loader {
+	l.beforeAutoMigrate = cb
+	return l
+}
```
Comment (giautm) [inline gormschema/gorm.go:173]: Use option pattern like `WithConfig()`

**Comment by luantranminh** [comment]
Looking at the unit test at the moment, the CREATE CONSTRAINT is not in the desired order, and it's also different when I run the test on my machine. 🏃‍♂️

**Comment by luantranminh** [comment]
I found interesting stuff here. GORM stores table relationships inside a Map. Looping through a Map is not guaranteed to produce the same order all the time.

https://github.com/go-gorm/gorm/blob/8c18714462de07fa3392b99eda089f2f9e3b6042/schema/schema.go#L186
image

We're looping through it here:
https://github.com/ariga/atlas-provider-gorm/blob/e5d6dbfb61aaf99a784b5f8641a8bcace527f1e7/gormschema/gorm.go#L147

It hurts our tests, but the migration files are fine. I'll submit another commit to sort the Relations out before looping.

**Comment by luantranminh** [comment]
Ronen said the forked project is missing Secrets to run the integration tests 
image

**Comment by giautm** [comment]
> Ronen said the forked project is missing Secrets to run the integration tests image

Yes, because the repo's secret doesn't share with the forked repository.

File: gormschema/gorm.go [hunk 5]
```diff
@@ -140,11 +146,20 @@ func (m *migrator) HasTable(dst any) bool {
...
 		err := m.Migrator.RunWithValue(model, func(stmt *gorm.Statement) error {
-			for _, rel := range stmt.Schema.Relationships.Relations {
+
+			relationNames := make([]string, 0, len(stmt.Schema.Relationships.Relations))
+			for name := range stmt.Schema.Relationships.Relations {
+				relationNames = append(relationNames, name)
+			}
+			// since Relations is a map, the order of the keys is not guaranteed
+			// so we sort the keys to make the sql output deterministic
+			sort.Strings(relationNames)
```
[the remark this answers is not in the document]
Comment (giautm) [reply gormschema/gorm.go:158]: Screenshot 2024-04-22 at 11 15 55

**Review by giautm — APPROVED** [review]

**Review by ronenlu — APPROVED** [review]
